/*public class UserAccount extends javax.swing.JFrame {

    public UserAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *//*
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
*//*
    /**
     * @param args the command line arguments
     *//*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *//*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserAccount().setVisible(true);
            }
        });
    }*//*

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
} */

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stms;

import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
/**
 *
 * @author User
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        super("Admin Dashboard");
        initComponents();
    }
    public void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        btnAddStudent = new javax.swing.JButton();
        btnViewAll = new javax.swing.JButton();
        btnViewCR = new javax.swing.JButton();
        btnMonthlySF = new javax.swing.JButton();
        btnManagePrAcc = new javax.swing.JButton();
        btnUpdateStudent = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnChangePass = new javax.swing.JButton();
        btnAboutUs = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(18, 44, 70));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 0, -1, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, -1, 60));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, -1, -1));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, -1, -1));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 580, 1670, 20));

        btnAddStudent.setBackground(new java.awt.Color(25, 25, 25));
        btnAddStudent.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        btnAddStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnAddStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/student.png"))); // NOI18N
        btnAddStudent.setText("<html>Manage Student<br>Record</html>");
        btnAddStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddStudentActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 380, 150));

        btnViewAll.setBackground(new java.awt.Color(25, 25, 25));
        btnViewAll.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        btnViewAll.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/list_1.png"))); // NOI18N
        btnViewAll.setText("View All Records");
        btnViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 340, 380, 150));

        btnViewCR.setBackground(new java.awt.Color(25, 25, 25));
        btnViewCR.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        btnViewCR.setForeground(new java.awt.Color(255, 255, 255));
        btnViewCR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/list_1.png"))); // NOI18N
        btnViewCR.setText("<html>View Classwise<br>Report</html>");
        btnViewCR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCRActionPerformed(evt);
            }
        });
        jPanel1.add(btnViewCR, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 100, 360, 150));

        btnMonthlySF.setBackground(new java.awt.Color(25, 25, 25));
        btnMonthlySF.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        btnMonthlySF.setForeground(new java.awt.Color(255, 255, 255));
        btnMonthlySF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/money.png"))); // NOI18N
        btnMonthlySF.setText("<html>Monthly School<br>Fund Allocation</html>");
        btnMonthlySF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonthlySFActionPerformed(evt);
            }
        });
        jPanel1.add(btnMonthlySF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 380, 150));

        btnManagePrAcc.setBackground(new java.awt.Color(25, 25, 25));
        btnManagePrAcc.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        btnManagePrAcc.setForeground(new java.awt.Color(255, 255, 255));
        btnManagePrAcc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update2.png"))); // NOI18N
        btnManagePrAcc.setText("<html>Manage Principal<br>Account</html>");
        btnManagePrAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePrAccActionPerformed(evt);
            }
        });
        jPanel1.add(btnManagePrAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 340, 360, 150));

        btnUpdateStudent.setBackground(new java.awt.Color(25, 25, 25));
        btnUpdateStudent.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        btnUpdateStudent.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update2.png"))); // NOI18N
        btnUpdateStudent.setText("<html>Update Student<br>Record</html>");
        btnUpdateStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateStudentActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdateStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 380, 150));

        btnLogout.setBackground(new java.awt.Color(6, 6, 17));
        btnLogout.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        btnLogout.setText(" Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 620, 310, 100));

        btnChangePass.setBackground(new java.awt.Color(6, 6, 17));
        btnChangePass.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnChangePass.setForeground(new java.awt.Color(255, 255, 255));
        btnChangePass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update2.png"))); // NOI18N
        btnChangePass.setText(" Change Password");
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });
        jPanel1.add(btnChangePass, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 620, 330, 100));

        btnAboutUs.setBackground(new java.awt.Color(6, 6, 17));
        btnAboutUs.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnAboutUs.setForeground(new java.awt.Color(255, 255, 255));
        btnAboutUs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/about.png"))); // NOI18N
        btnAboutUs.setText(" About Us");
        btnAboutUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutUsActionPerformed(evt);
            }
        });
        jPanel1.add(btnAboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 620, 310, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1660, 770));

        jPanel2.setBackground(new java.awt.Color(6, 22, 38));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 90)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin2.png"))); // NOI18N
        jLabel1.setText("Admin dashboard");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1660, 150));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        


    private void btnAddStudentActionPerformed(java.awt.event.ActionEvent evt) {                                              
        ManageStudentRecord msr=new ManageStudentRecord();
        msr.setVisible(true);
        close();
    }                                             

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {                                          
        Login lg=new Login();
        lg.setVisible(true);
        close();        // TODO add your handling code here:
    }                                         

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {                                              
        AdminPassword ap=new AdminPassword();
        ap.setVisible(true);
        close();
    }                                             

    private void btnAboutUsActionPerformed(java.awt.event.ActionEvent evt) {                                           
        AboutUs_Admin au=new AboutUs_Admin();
        au.setVisible(true);
        close();        // TODO add your handling code here:
    }                                          

    private void btnUpdateStudentActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        UpdateStudentRecord usr=new UpdateStudentRecord();
        usr.setVisible(true);
        close();
    }                                                
    private void btnViewCRActionPerformed(java.awt.event.ActionEvent evt) {                                          
        ClasswiseReportAdmin cra=new ClasswiseReportAdmin();
        cra.setVisible(true);
        close();
    }                                         

    private void btnMonthlySFActionPerformed(java.awt.event.ActionEvent evt) {                                             
        MonthlyAllocationFund maf=new MonthlyAllocationFund();
        maf.setVisible(true);
        close();
    }                                            

    private void btnViewAllActionPerformed(java.awt.event.ActionEvent evt) {                                           
        ViewAll_Admin va_a=new ViewAll_Admin();
        va_a.setVisible(true);
        close();
    }                                          

    private void btnManagePrAccActionPerformed(java.awt.event.ActionEvent evt) {                                               
        MngPrincipalAcc mg=new MngPrincipalAcc();
        mg.setVisible(true);
        close();
    }  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAboutUs;
    private javax.swing.JButton btnAddStudent;
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManagePrAcc;
    private javax.swing.JButton btnMonthlySF;
    private javax.swing.JButton btnUpdateStudent;
    private javax.swing.JButton btnViewAll;
    private javax.swing.JButton btnViewCR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration                   
}
