/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *//*
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     *//*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel *//*
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *//*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form *//*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStudentRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
*/
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stms;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.util.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class ManageStudentRecord extends javax.swing.JFrame {

    /**
     * Creates new form AddStudentRecord
     */
    public ManageStudentRecord() {
        super("Manage Student Records");
        initComponents();
        fillCombo();
    }
 public void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAccount = new javax.swing.JTextField();
        txtAadhar = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtFather = new javax.swing.JTextField();
        txtMother = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtBank = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        btnDelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSave1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        comboClasses = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnView = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(18, 44, 70));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bank Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, 230, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Account number");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 720, 250, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Class-Section");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 230, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Aadhar number");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 230, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Student's Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 240, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Father's Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 230, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mother's Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 230, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Phone number");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 230, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 230, 40));

        txtAccount.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jPanel1.add(txtAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 720, 500, 50));

        txtAadhar.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jPanel1.add(txtAadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 500, 50));

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 500, 50));

        txtFather.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jPanel1.add(txtFather, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 500, 50));

        txtMother.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jPanel1.add(txtMother, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 500, 50));

        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 500, 50));

        txtBank.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        txtBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankActionPerformed(evt);
            }
        });
        jPanel1.add(txtBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, 500, 50));

        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 500, 100));

        btnDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnDelete.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 500, 260, 90));
        
        btnClear.setBackground(new java.awt.Color(204, 204, 204));
        btnClear.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 300, 260, 70));

        btnSave1.setBackground(new java.awt.Color(204, 204, 204));
        btnSave1.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        btnSave1.setText("Save");
        btnSave1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 660, 260, 90));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 23)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("<html>Enter Aadhar number <br>to delete a record</html>");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 400, 310, 100));

        comboClasses.setFont(new java.awt.Font("Segoe UI", 0, 23)); // NOI18N
        comboClasses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Class--" }));
        comboClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboClassesActionPerformed(evt);
            }
        });
        jPanel1.add(comboClasses, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 500, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 1400, 800));

        jPanel2.setBackground(new java.awt.Color(6, 22, 38));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 82)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/student2.png")));
        jLabel2.setText(" Manage Student Record");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 1150, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 0, 1400, 150));

        jPanel3.setBackground(new java.awt.Color(6, 6, 17));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnView.setBackground(new java.awt.Color(6, 6, 17));
        btnView.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/list.png"))); // NOI18N
        btnView.setText("<html>View All<br>Records</html>");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel3.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 250, 120));

        btnLogout.setBackground(new java.awt.Color(6, 6, 17));
        btnLogout.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 760, 250, 120));

        btnHome.setBackground(new java.awt.Color(6, 6, 17));
        btnHome.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        btnHome.setText("Home");
        jPanel3.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 250, 120));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 950));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        
    void insert_data()
    {   
        Object selectedItem = comboClasses.getSelectedItem();
        String classsection = selectedItem.toString();
        long Aadhar_no=Long.parseLong(txtAadhar.getText());
        String Student_name=txtName.getText();
        String Father_name=txtFather.getText();
        String Mother_name=txtMother.getText();
        long Phone_no=Long.parseLong(txtPhone.getText());
        
        String Address=txtAddress.getText();
        String Bank_name=txtBank.getText();
        long Account_no=Long.parseLong(txtAccount.getText());
        
        int counter=0;
        
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/Transaction_Mgmt","root","");
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from student_details_abcss");
            while(rs.next())
            {
                if(Aadhar_no==rs.getLong(1))
                {
                    counter++;
                }
            }
            if(counter>0)
            {
                JOptionPane.showMessageDialog(this,"Student associated with the Aadhar number already exists in the database!");
                txtAadhar.setText("");
                counter=0;
            }
            else
            {
                insert();
            }
  
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }
    void insert()
    {
        Object selectedItem = comboClasses.getSelectedItem();
        String classsection = selectedItem.toString();
        long Aadhar_no=Long.parseLong(txtAadhar.getText());
        String Student_name=txtName.getText();
        String Father_name=txtFather.getText();
        String Mother_name=txtMother.getText();
        long Phone_no=Long.parseLong(txtPhone.getText());
        
        String Address=txtAddress.getText();
        String Bank_name=txtBank.getText();
        long Account_no=Long.parseLong(txtAccount.getText());
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/Transaction_Mgmt","root","");
            Statement stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery("select * from student_details_abcss");
            if(rs.next())
            {
                PreparedStatement pst=conn.prepareStatement("insert into student_details_abcss(Aadhar_no, Student_name, Father_name, Mother_name, Address, Phone_no, Bank_name, Account_no, Class_section) values(?,?,?,?,?,?,?,?,?)");
                pst.setLong(1,Aadhar_no);
                pst.setString(2,Student_name);
                pst.setString(3,Father_name);
                pst.setString(4,Mother_name);
                pst.setString(5,Address);
                pst.setLong(6,Phone_no);
                pst.setString(7,Bank_name);
                pst.setLong(8,Account_no);
                pst.setString(9, classsection);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"New student record added successfully");
            }
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }
    void delete_data()
    {
        try
        {
                String aadhar=txtAadhar.getText();
                
                Class.forName("com.mysql.jdbc.Driver");
                Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/Transaction_Mgmt","root","");
                Statement stmt=conn.createStatement();
                ResultSet rs=stmt.executeQuery("select * from student_details_abcss where Aadhar_no='"+aadhar+"'");
                if(rs.next())
                {
                   //int aid=Integer.parseInt(txtAadhar.getText());
                   PreparedStatement pst=conn.prepareStatement("delete from student_details_abcss where Aadhar_no=?");
                   pst.setString(1,aadhar);
                   pst.executeUpdate();
                   JOptionPane.showMessageDialog(this,"Record has been deleted successfully");
                   cleartext();
                   conn.close();  
                }
                else
                {
                   JOptionPane.showMessageDialog(this, "Enter a valid Aadhar Number");
                }
                 
           }
        catch(Exception ex){ex.printStackTrace();}
    }
    public void fillCombo()
    {
        try
        {
            String querycombo="select class_section from class_details_abcss";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/transaction_mgmt", "root", "");
            PreparedStatement pst=conn.prepareStatement(querycombo);
            ResultSet rs=pst.executeQuery();
            while(rs.next())
            {
                String classsection=rs.getString("class_section");
                comboClasses.addItem(classsection);
            }
            
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    void cleartext()
    {
        comboClasses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Class--" }));
        fillCombo();
        txtAadhar.setText("");
        txtName.setText("");
        txtFather.setText("");
        txtMother.setText("");
        txtPhone.setText("");
        txtAddress.setText("");
        txtBank.setText("");
        txtAccount.setText("");
    }
    private void txtBankActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {                                          
       delete_data();
    }  
    
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {                                          
       cleartext();
    }  

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {                                          
        Login lg=new Login();
        lg.setVisible(true);
        close();
       
    }                                         

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {                                        
                                                
        ViewAll_Admin ad=new ViewAll_Admin();
        ad.setVisible(true);
        close();
    
    }                                       

    private void btnSave1ActionPerformed(java.awt.event.ActionEvent evt) { 
        Object selectedItem = comboClasses.getSelectedItem();
        String classsection = selectedItem.toString();
        String aadhar_no=txtAadhar.getText();
        String student=txtName.getText();
        String father=txtFather.getText();
        String mother=txtMother.getText();
        String phoneno=txtPhone.getText();
        String address=txtAddress.getText();
        String bankname=txtBank.getText();
        String account=txtAccount.getText();
        
        if ((aadhar_no.trim().equals("") || student.trim().equals(""))||father.trim().equals("")||mother.trim().equals("")||phoneno.trim().equals("")||address.trim().equals("")||bankname.trim().equals("")||account.trim().equals("")||classsection.trim().equals("---class---"))
        {
            JOptionPane.showMessageDialog(this, "Enter complete student details");
        }
        else
        {
            insert_data();
        } 
        
    }                                        
   private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {                                        
        AdminDashboard ad=new AdminDashboard();
        ad.setVisible(true);
        close();
    }
    private void comboClassesActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStudentRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify  
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSave1;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> comboClasses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAadhar;
    private javax.swing.JTextField txtAccount;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtBank;
    private javax.swing.JTextField txtFather;
    private javax.swing.JTextField txtMother;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration                   
}
