/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stms;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.*;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author seema
 */
public class PrintReceipt extends javax.swing.JFrame {

    /**
     * Creates new form PrintReceipt
     */
    public PrintReceipt() {
        super("Print Receipt");
        initComponents();
        getRecords();
        getRecords2();
        amtWords();
    }
    public void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    void getRecords()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/transaction_mgmt", "root", "");
            PreparedStatement pst=conn.prepareStatement("select * from money_transfer_details_abcss order by receipt_no desc limit 1");
            ResultSet rs=pst.executeQuery();
            rs.next();
            lblReceiptNo.setText(rs.getString("receipt_no"));
            lblAadharNo.setText(rs.getString("aadhar_no"));
            lblDate.setText(rs.getString("date"));
            lblAmount.setText(Integer.toString(rs.getInt("amount")));
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }
    void getRecords2()
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/transaction_mgmt", "root", "");
            PreparedStatement pst=conn.prepareStatement("select * from student_details_abcss where aadhar_no = (select aadhar_no from money_transfer_details_abcss order by receipt_no desc limit 1)");
            ResultSet rs=pst.executeQuery();
            rs.next();
            lblAccount.setText(Long.toString(rs.getLong("account_no")));
            lblBank.setText(rs.getString("bank_name"));
            lblStudent.setText(rs.getString("student_name"));
            lblPhoneNo.setText(Long.toString(rs.getLong("phone_no")));
            lblAddress.setText(rs.getString("address"));
            lblClass.setText(rs.getString("class_section"));
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }
    void printReceipt() throws PrinterException
    {
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.40,0.40);
                
                jPanel3.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
            job.print();
        }
    }
    void amtWords()
    {
        int amount=Integer.parseInt(lblAmount.getText());
        //NumberToWordsConverter ntw= new NumberToWordsConverter();
        txtWords.setText(NumberToWordsConverter.converts(amount)+" Rupees Only");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblReceiptNo = new javax.swing.JLabel();
        lblBank = new javax.swing.JLabel();
        lblAadharNo = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblAccount = new javax.swing.JLabel();
        lblStudent = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblPhoneNo = new javax.swing.JLabel();
        lblClass = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        txtWords = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(18, 44, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(6, 6, 17));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHome.setBackground(new java.awt.Color(6, 6, 17));
        btnHome.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        btnHome.setText(" Home");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel2.add(btnHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 220, 110));

        btnLogout.setBackground(new java.awt.Color(6, 6, 17));
        btnLogout.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        btnLogout.setText(" Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 710, 220, 110));

        btnPrint.setBackground(new java.awt.Color(6, 6, 17));
        btnPrint.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/printer-.png"))); // NOI18N
        btnPrint.setText("<html> Print <br> Receipt</html>");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel2.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 220, 110));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 930));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 75)); // NOI18N
        jLabel1.setText(" ABC Secondary School");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Perpetua", 0, 38)); // NOI18N
        jLabel2.setText("District 18, Shanti Vihar Marg, Lucknow, Uttar Pradesh - 226012");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clg_1.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 200, 170));

        jPanel4.setBackground(new java.awt.Color(6, 6, 17));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1530, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 1530, 10));

        jLabel4.setFont(new java.awt.Font("MS PGothic", 0, 30)); // NOI18N
        jLabel4.setText("<html>Class and<br>Section</html>");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 670, 180, -1));

        jLabel6.setFont(new java.awt.Font("MS PGothic", 0, 30)); // NOI18N
        jLabel6.setText("Bank name");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 200, -1));

        jLabel7.setFont(new java.awt.Font("MS PGothic", 0, 30)); // NOI18N
        jLabel7.setText("Account no.");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 210, -1));

        jLabel8.setFont(new java.awt.Font("MS PGothic", 0, 30)); // NOI18N
        jLabel8.setText("Student name");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 220, -1));

        jLabel9.setFont(new java.awt.Font("MS PGothic", 0, 30)); // NOI18N
        jLabel9.setText("Address");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 150, -1));

        jLabel10.setFont(new java.awt.Font("MS PGothic", 0, 30)); // NOI18N
        jLabel10.setText("Aadhar no.");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 310, 200, -1));

        jLabel11.setFont(new java.awt.Font("MS PGothic", 0, 30)); // NOI18N
        jLabel11.setText("Phone number");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 600, 220, -1));

        jLabel12.setFont(new java.awt.Font("MS PGothic", 0, 30)); // NOI18N
        jLabel12.setText("Amount");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 760, 150, -1));

        jLabel13.setFont(new java.awt.Font("MS PGothic", 0, 30)); // NOI18N
        jLabel13.setText("Total Amount ( in words )");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 830, 360, -1));

        jLabel14.setFont(new java.awt.Font("MS PGothic", 0, 30)); // NOI18N
        jLabel14.setText("Date of transfer");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 250, -1));

        jLabel15.setFont(new java.awt.Font("MS PGothic", 0, 30)); // NOI18N
        jLabel15.setText("Receipt no.");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 200, -1));

        lblReceiptNo.setFont(new java.awt.Font("MS PGothic", 1, 28)); // NOI18N
        lblReceiptNo.setText(" .............");
        jPanel3.add(lblReceiptNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 200, 40));

        lblBank.setFont(new java.awt.Font("MS PGothic", 1, 28)); // NOI18N
        lblBank.setText(" .............");
        jPanel3.add(lblBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 280, 40));

        lblAadharNo.setFont(new java.awt.Font("MS PGothic", 1, 28)); // NOI18N
        lblAadharNo.setText(" .............");
        jPanel3.add(lblAadharNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 300, 340, 40));

        lblDate.setFont(new java.awt.Font("MS PGothic", 1, 28)); // NOI18N
        lblDate.setText(" .............");
        jPanel3.add(lblDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 230, 260, 40));

        lblAccount.setFont(new java.awt.Font("MS PGothic", 1, 28)); // NOI18N
        lblAccount.setText(" .............");
        jPanel3.add(lblAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, 310, 40));

        lblStudent.setFont(new java.awt.Font("MS PGothic", 1, 28)); // NOI18N
        lblStudent.setText(" .............");
        jPanel3.add(lblStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 620, 40));

        lblAddress.setFont(new java.awt.Font("MS PGothic", 1, 28)); // NOI18N
        lblAddress.setText(" .............");
        jPanel3.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 510, 930, 50));

        lblPhoneNo.setFont(new java.awt.Font("MS PGothic", 1, 28)); // NOI18N
        lblPhoneNo.setText(" .............");
        jPanel3.add(lblPhoneNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 590, 290, 40));

        lblClass.setFont(new java.awt.Font("MS PGothic", 1, 28)); // NOI18N
        lblClass.setText(" .............");
        jPanel3.add(lblClass, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 670, 200, 40));

        lblAmount.setFont(new java.awt.Font("MS PGothic", 1, 28)); // NOI18N
        lblAmount.setText(" .............");
        jPanel3.add(lblAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 750, 200, 40));

        txtWords.setFont(new java.awt.Font("MS PGothic", 1, 28)); // NOI18N
        txtWords.setText("  ");
        txtWords.setBorder(null);
        txtWords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWordsActionPerformed(evt);
            }
        });
        jPanel3.add(txtWords, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 820, 530, 50));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 1470, 900));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1810, 930));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        PrincipalDashboard pd=new PrincipalDashboard();
        pd.setVisible(true);
        close();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Login lg=new Login();
        lg.setVisible(true);
        close();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try {
            printReceipt();
        } catch (PrinterException ex) {
            Logger.getLogger(PrintReceipt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void txtWordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWordsActionPerformed
        int amount=Integer.parseInt(lblAmount.getText());
        txtWords.setText(Integer.toString(amount));
    }//GEN-LAST:event_txtWordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAadharNo;
    private javax.swing.JLabel lblAccount;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblBank;
    private javax.swing.JLabel lblClass;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPhoneNo;
    private javax.swing.JLabel lblReceiptNo;
    private javax.swing.JLabel lblStudent;
    private javax.swing.JTextField txtWords;
    // End of variables declaration//GEN-END:variables
}
