/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stms;

import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author seema
 */
public class PrincipalDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard
     */
    public PrincipalDashboard() {
        super("Principal Dashboard");
        initComponents();
    }
    public void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnUserAccount = new javax.swing.JButton();
        btnMoneyTransfer = new javax.swing.JButton();
        btnClassDetails = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnViewAll = new javax.swing.JButton();
        btnClassReport = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jButton5.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(18, 44, 70));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUserAccount.setBackground(new java.awt.Color(25, 25, 25));
        btnUserAccount.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        btnUserAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnUserAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin.png"))); // NOI18N
        btnUserAccount.setText("User Account");
        btnUserAccount.setBorder(null);
        btnUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserAccountActionPerformed(evt);
            }
        });
        jPanel3.add(btnUserAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 340, 380, 170));

        btnMoneyTransfer.setBackground(new java.awt.Color(25, 25, 25));
        btnMoneyTransfer.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        btnMoneyTransfer.setForeground(new java.awt.Color(255, 255, 255));
        btnMoneyTransfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/money.png"))); // NOI18N
        btnMoneyTransfer.setText("<html>Perform Money<br>Transfer</html>");
        btnMoneyTransfer.setBorder(null);
        btnMoneyTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoneyTransferActionPerformed(evt);
            }
        });
        jPanel3.add(btnMoneyTransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 380, 170));

        btnClassDetails.setBackground(new java.awt.Color(25, 25, 25));
        btnClassDetails.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        btnClassDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnClassDetails.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/class.png"))); // NOI18N
        btnClassDetails.setText("<html>Edit and<br>View Classes</html>");
        btnClassDetails.setBorder(null);
        btnClassDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassDetailsActionPerformed(evt);
            }
        });
        jPanel3.add(btnClassDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 380, 170));

        btnAbout.setBackground(new java.awt.Color(6, 6, 17));
        btnAbout.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnAbout.setForeground(new java.awt.Color(255, 255, 255));
        btnAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/about.png"))); // NOI18N
        btnAbout.setText("About Us");
        btnAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAboutActionPerformed(evt);
            }
        });
        jPanel3.add(btnAbout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 620, 290, 100));

        btnLogout.setBackground(new java.awt.Color(6, 6, 17));
        btnLogout.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        btnLogout.setText(" Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 620, 290, 100));

        btnSearch.setBackground(new java.awt.Color(25, 25, 25));
        btnSearch.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search2.png"))); // NOI18N
        btnSearch.setText("Search Records");
        btnSearch.setBorder(null);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel3.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 380, 170));

        btnViewAll.setBackground(new java.awt.Color(25, 25, 25));
        btnViewAll.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        btnViewAll.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/list_1.png"))); // NOI18N
        btnViewAll.setText("<html>View All<br>Records</html>");
        btnViewAll.setBorder(null);
        btnViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllActionPerformed(evt);
            }
        });
        jPanel3.add(btnViewAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 80, 380, 170));

        btnClassReport.setBackground(new java.awt.Color(25, 25, 25));
        btnClassReport.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        btnClassReport.setForeground(new java.awt.Color(255, 255, 255));
        btnClassReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/report.png"))); // NOI18N
        btnClassReport.setText("<html>View Classwise<br>Report</html>");
        btnClassReport.setBorder(null);
        btnClassReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClassReportActionPerformed(evt);
            }
        });
        jPanel3.add(btnClassReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 340, 380, 170));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 1710, 10));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 1700, 750));

        jPanel4.setBackground(new java.awt.Color(6, 22, 38));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 98)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/admin2.png"))); // NOI18N
        jLabel2.setText(" Principal dashboard");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1700, 170));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoneyTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoneyTransferActionPerformed
        PerformMoneyTransfer pmt = new PerformMoneyTransfer();
        pmt.setVisible(true);
        close();
    }//GEN-LAST:event_btnMoneyTransferActionPerformed

    private void btnClassDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassDetailsActionPerformed
        ClassAndSection cas=new ClassAndSection();
        cas.setVisible(true);
        close();
    }//GEN-LAST:event_btnClassDetailsActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAboutActionPerformed
        AboutUs au=new AboutUs();
        au.setVisible(true);
        close();
    }//GEN-LAST:event_btnAboutActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        Login lg=new Login();
        lg.setVisible(true);
        close();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        SearchStudentRecords ssr=new SearchStudentRecords();
        ssr.setVisible(true);
        close();
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserAccountActionPerformed
        UserAccount ua=new UserAccount();
        ua.setVisible(true);
        close();
    }//GEN-LAST:event_btnUserAccountActionPerformed

    private void btnViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllActionPerformed
        ViewAll_Principal va_p=new ViewAll_Principal();
        va_p.setVisible(true);
        close();
    }//GEN-LAST:event_btnViewAllActionPerformed

    private void btnClassReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClassReportActionPerformed
        ClasswiseReport cr=new ClasswiseReport();
        cr.setVisible(true);
        close();
    }//GEN-LAST:event_btnClassReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnClassDetails;
    private javax.swing.JButton btnClassReport;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMoneyTransfer;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUserAccount;
    private javax.swing.JButton btnViewAll;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
