/*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     *//*
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     *//*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel *//*
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *//*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form *//*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStudentRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
*/
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stms;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.util.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class UpdateStudentRecord extends javax.swing.JFrame {

    /**
     * Creates new form UpdateStudentRecord
     */
public UpdateStudentRecord() {
        super("Update Student Record");
        initComponents();
        fillCombo();
    }
public void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
    }
public void fillCombo()
    {
        try
        {
            String querycombo="select class_section from class_details_abcss";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/transaction_mgmt", "root", "");
            PreparedStatement pst=conn.prepareStatement(querycombo);
            ResultSet rs=pst.executeQuery();
            while(rs.next())
            {
                String classsection=rs.getString("class_section");
                comboClasses.addItem(classsection);
            }
            
            
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
    }

    void cleartext()
    {
        comboClasses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Class--" }));
        fillCombo();
        txtAadhar.setText("");
        txtName.setText("");
        txtFather.setText("");
        txtMother.setText("");
        txtPhone.setText("");
        txtAddress.setText("");
        txtBank.setText("");
        txtAccount.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtAccount = new javax.swing.JTextField();
        txtAadhar = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtFather = new javax.swing.JTextField();
        txtMother = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtBank = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        btnEnter = new javax.swing.JButton();
        comboClasses = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnUpdate1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnClear = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(6, 22, 38));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 85)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update3.png"))); // NOI18N
        jLabel2.setText(" Update Student Record");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 1190, 120));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 1390, 150));

        jPanel1.setBackground(new java.awt.Color(18, 44, 70));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bank Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 640, 240, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Account number");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 710, 240, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Class-Section");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 240, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Aadhar number");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 240, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Student's Name");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 240, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Father's Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 240, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mother's Name");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 240, 40));

        jLabel10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Phone number");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 240, 40));

        jLabel11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Address");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 240, 40));

        txtAccount.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jPanel1.add(txtAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 720, 470, 50));

        txtAadhar.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        txtAadhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAadharActionPerformed(evt);
            }
        });
        jPanel1.add(txtAadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 470, 50));

        txtName.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jPanel1.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 110, 470, 50));

        txtFather.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jPanel1.add(txtFather, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 470, 50));

        txtMother.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jPanel1.add(txtMother, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 470, 50));

        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        jPanel1.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 470, 50));

        txtBank.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        txtBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankActionPerformed(evt);
            }
        });
        jPanel1.add(txtBank, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 640, 470, 50));

        txtAddress.setColumns(20);
        txtAddress.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        txtAddress.setRows(5);
        jScrollPane1.setViewportView(txtAddress);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 470, 100));

        btnEnter.setBackground(new java.awt.Color(204, 204, 204));
        btnEnter.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        btnEnter.setText("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });
        jPanel1.add(btnEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 30, 220, 80));
        
        btnClear.setBackground(new java.awt.Color(204, 204, 204));
        btnClear.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 570, 220, 70));

        comboClasses.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        comboClasses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Classes--" }));
        jPanel1.add(comboClasses, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 470, 50));

        jLabel1.setFont(new java.awt.Font("SansSerif", 2, 23)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Press enter to fetch details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 110, 280, 40));

        btnUpdate1.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdate1.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        btnUpdate1.setText("Update");
        btnUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdate1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 690, 220, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 1390, 800));

        jPanel3.setBackground(new java.awt.Color(6, 6, 17));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnView.setBackground(new java.awt.Color(6, 6, 17));
        btnView.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        btnView.setForeground(new java.awt.Color(255, 255, 255));
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/list.png"))); // NOI18N
        btnView.setText("<html>View All<br>Records</html>");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });
        jPanel3.add(btnView, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 580, 270, 130));

        btnLogout.setBackground(new java.awt.Color(6, 6, 17));
        btnLogout.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        btnLogout.setText(" Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 770, 270, 130));

        btnBack.setBackground(new java.awt.Color(6, 6, 17));
        btnBack.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.png"))); // NOI18N
        btnBack.setText(" Home");
        jPanel3.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 270, 130));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 950));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void txtBankActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {                                         
       setRecords();
        
    }                                        

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {                                        
        ViewAll_Admin ad=new ViewAll_Admin();
        ad.setVisible(true);
        close();
    }                                       

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {                                          
        Login lg=new Login();
        lg.setVisible(true);
        close();

    }                                         

    private void btnUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        update_record();
       
    }  
    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {                                          
       cleartext();
    }

    private void txtAadharActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
    }                                         
private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {                                        
        AdminDashboard ad=new AdminDashboard();
        ad.setVisible(true);
        close();
    }
public void setRecords()
{
    
    try
    {
        Class.forName("com.mysql.jdbc.Driver");
        Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/transaction_mgmt", "root", "");
        
        String aadhar=txtAadhar.getText();
        Statement stmt=conn.createStatement();
        ResultSet rs=stmt.executeQuery("select * from student_details_abcss where Aadhar_no='"+aadhar+"'");
        if(rs.next())
        {
            PreparedStatement pst=conn.prepareStatement("select * from student_details_abcss where Aadhar_no='"+aadhar+"'");
            ResultSet rs1=pst.executeQuery();
            rs1.next();
            txtName.setText(rs.getString("student_name"));
            txtFather.setText(rs.getString("father_name"));
            txtMother.setText(rs.getString("mother_name"));
            txtAddress.setText(rs.getString("Address"));
            txtPhone.setText(rs.getString("phone_no"));
            txtBank.setText(rs.getString("bank_name"));
            txtAccount.setText(rs.getString("account_no"));
            comboClasses.setSelectedItem(rs.getString("class_section"));
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Enter a valid Aadhar Number");
        }

    }
    catch(Exception e)
    {
        e.printStackTrace();
    }
}
void update_record()
{
    try
    {
            
            String Aadhar=txtAadhar.getText();
            String Name=txtName.getText();
            String Fname=txtFather.getText();
            String Mname=txtMother.getText();
            String Address=txtAddress.getText();
            String Phone=txtPhone.getText();
            String Bank=txtBank.getText();
            String Account=txtAccount.getText();
            String Classes=(String) comboClasses.getSelectedItem();
            Statement stmt=null;
            
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/transaction_mgmt", "root", "");
            String query = ("select * from Student_details_abcss where Aadhar_no='"+Aadhar+"' ");   
            stmt=conn.createStatement();
            ResultSet rs=stmt.executeQuery(query);
            
            boolean status=rs.next();
            if(status)
            {
                PreparedStatement pst=conn.prepareStatement("update Student_details_abcss set Student_name=?, Father_name=?, Mother_name=?, Address=?, Phone_no=?, Bank_name=?, Account_no=?, Class_section=? where Aadhar_no=?");
                
                pst.setString(1,Name);
                pst.setString(2,Fname);
                pst.setString(3,Mname);
                pst.setString(4,Address);
                pst.setString(5,Phone);
                pst.setString(6,Bank);
                pst.setString(7,Account);
                pst.setString(8,Classes);
                pst.setString(9,Aadhar);
                pst.executeUpdate();
                JOptionPane.showMessageDialog(this,"Data changed successfully");
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Please enter correct Aadhar number!");
            }
    }catch(Exception e){e.printStackTrace();}
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateStudentRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify  
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnUpdate1;
    private javax.swing.JButton btnView;
    private javax.swing.JComboBox<String> comboClasses;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtAadhar;
    private javax.swing.JTextField txtAccount;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtBank;
    private javax.swing.JTextField txtFather;
    private javax.swing.JTextField txtMother;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration                   
}
